### ISSUE TITLE
Projet PHP

### ISSUE THREAD

**Issue by kimil14** [cfHxqA/InnoGames.FoE.Bot#15]
Bonjour, j'ai la même idée que vous mais en PHP cependant je bloque sur le fait d'envoyer en Curl JSON. Pouvez vous m'aidez si je vous passe mon code ?

Hello, I have the same idea as you but in PHP however I block on sending in JSON Curl. Can you help me if I pass you my code?

http://team-h14.fr.cr/?page=curl

**Comment by kimil14** [comment]
<?php 

$login = "****";
$password = "****";
$lang = "fr";
$world = "fr7";

/*ON RECUP LE TOKEN ET ON CRÉÉ LE COOKIE*/
$token = requette_curl("https://$lang.forgeofempires.com/", "cookies_foe.txt");

/*ON SE CONNECTE ET ON MET A JOUR LE COOKIE*/
echo requette_curl_post("https://$lang.forgeofempires.com/glps/login_check", "cookies_foe.txt", "login[remember_me]=true&login[userid]=$login&login[password]=$password", $token);

/*ON AFFICHE LES MONDES*/
$mondes = requette("https://".$lang."0.forgeofempires.com/start/index?action=fetch_worlds_for_login_page","cookies_foe.txt", "");

/*ON LANCE LE JEU AVEC LE MONDE SELECTIONNE*/
$data = [
  "world_id" => $world
];
$json = json_encode($data);
$requette = requette("https://".$lang."0.forgeofempires.com/start/index?action=play_now_login","cookies_foe.txt", "json=$json");

/*ON SE CONNECTE AU JEU AVEC LA SESSION EN COURS*/
$pattern = '/\{(?:[^{}]|(?R))*\}/x';
preg_match_all($pattern, $requette, $matches);
$requette1 = json_decode($matches[0][0], true);

/*ON RECUPERE L'URL GATEWAY POUR LES INFOS DU JOUEUR ET DES RESSOURCES*/
$requette2 = requette($requette1["login_url"],"cookies_foe.txt", "");
preg_match("/'string_gatewayUrl': '(.*)'/", $requette2, $matches2);
preg_match("/'string_urlSuffix': '(.*)'/", $requette2, $matches3);
$url_gateway = $matches2[1];
$url_gatewayTime = $matches3[1];
$code = explode("h=",$url_gateway);

echo "<br />Mon url gateway: ".$url_gateway;
echo "<br />Mon code gateway: ".$code[1];
echo "<br />Mon url gateway Time: ".$url_gatewayTime;

$payload = [
	"__class__" => "ServerRequest",
	"requestClass" => "StartupService",
	"requestData" => [],
	"requestId" => 0,
	"requestMethod" => "getData"
];
$signature = md5($code[1]."UqO1UDI2SsDYiL/l1sANc/xCeiOXtMw5TQvcgAJgEBmcbNFbG+zS0HvqoQSOBFfRENW+JmfutSmK/8J/UsnZgw==".json_encode($payload));
$signature = substr($signature, 0, 10);
echo "<br />signature: ".$signature;
echo "<br /> payload: ".json_encode($payload);
echo "<br /> content length: ".strlen(json_encode($payload));

/*ON AFFICHE LES RESSOURCES*/
$requette3 = requette2($url_gateway,"cookies_foe.txt", json_encode($payload), $url_gatewayTime, $signature);
echo $requette3;

function requette_curl($url, $cookie){
	$userAgent  = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36';
	//$url = "https://gamekit.com/rate/";
	$ch = curl_init();
	if (preg_match('`^https://`i', $url)) 
	{ 
	  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); 
	  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
	} 
	//curl_setopt($ch, CURLOPT_COOKIESESSION, true);
	curl_setopt($ch, CURLOPT_COOKIEFILE, $cookie);
	curl_setopt($ch, CURLOPT_COOKIEJAR,  $cookie);
	curl_setopt($ch, CURLOPT_USERAGENT,  $userAgent); // empty user agents probably not accepted
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
	curl_setopt($ch, CURLOPT_AUTOREFERER,    1); // enable this - they check referer on POST
	curl_setopt($ch, CURLOPT_URL, $url); 	
	 curl_setopt($ch, CURLOPT_HEADER, 1);
	$html = curl_exec($ch); 
	curl_close($ch);
	 $token  = extractCookies2(file_get_contents($cookie));
	return $token;
}
function extractCookies2($string) {
    $cookies = array();
    
    $lines = explode("\n", $string);
 
    // iterate over lines
    foreach ($lines as $line) {
 
        // we only care for valid cookie def lines
        if (isset($line[0]) && substr_count($line, "\t") == 6) {
 
            // get tokens in an array
            $tokens = explode("\t", $line);
 
            // trim the tokens
            $tokens = array_map('trim', $tokens);
 
            $cookie = array();
 
            // Extract the data
            $cookie['domain'] = $tokens[0];
            $cookie['flag'] = $tokens[1];
            $cookie['path'] = $tokens[2];
            $cookie['secure'] = $tokens[3];
 
            // Convert date to a readable format
            $cookie['expiration'] = date('Y-m-d h:i:s', $tokens[4]);
 
            $cookie['name'] = $tokens[5];

            $cookie['value'] = $tokens[6];
 			if($cookie['name'] == "XSRF-TOKEN"){
				return $cookie['value'];
			}
            // Record the cookie.
            $cookies[] = $cookie;
        }
    }
    
    return $cookies;
}
function requette_curl_post($url, $cookie, $post, $tok){
		global $lang;
		$headers = array();
		$headers[] = 'Accept: application/json, text/plain, */*'; 
		$headers[] = 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4';
		//$headers[] = 'Accept-Encoding: gzip, deflate, br';
		$headers[] = 'Content-Type: application/x-www-form-urlencoded; charset=utf-8';
		$headers[] = 'X-Requested-With: XMLHttpRequest';
		$headers[] = 'Origin: https://fr.forgeofempires.com';
		$headers[] = 'X-XSRF-TOKEN: ' .  $tok;
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch,CURLOPT_URL,$url);
		curl_setopt($ch, CURLOPT_REFERER, "https://$lang.forgeofempires.com/glps/iframe-login");
		curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36");          
		curl_setopt($ch, CURLOPT_COOKIEFILE, $cookie);
		curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie);
		curl_setopt($ch, CURLOPT_VERBOSE, 1);
		curl_setopt($ch, CURLOPT_NOBODY, 0);    
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt( $ch, CURLOPT_POST, true );
		curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
		curl_setopt($ch,CURLOPT_HEADER,0);
		$linkhtml = curl_exec($ch);
		curl_close($ch);
		return $linkhtml; 
	}

function requette($url, $cookie, $post){
	$headers = array();
	$headers[] = 'Accept: application/json, text/javascript, */*; q=0.01'; 
	$headers[] = 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4';
	//$headers[] = 'Content-Length: '.strlen($post);
	$headers[] = 'Content-Type: application/x-www-form-urlencoded; charset=utf-8';
	$headers[] = 'X-Requested-With: XMLHttpRequest';
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch,CURLOPT_URL,$url);
	curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36");          
	curl_setopt($ch, CURLOPT_COOKIEFILE, $cookie);
	curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie);
	curl_setopt($ch, CURLOPT_VERBOSE, 1);
	curl_setopt($ch, CURLOPT_NOBODY, 0);    
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt( $ch, CURLOPT_POST, true );
	curl_setopt( $ch, CURLOPT_POSTFIELDS, $post );
	curl_setopt($ch,CURLOPT_HEADER,0);
	$linkhtml=curl_exec($ch);
	curl_close($ch);
	return $linkhtml; 
}
function requette2($url, $cookie, $post, $time, $signature){
	$headers = array();
	//$headers[] = 'Accept: application/json,text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'; 
	//$headers[] = 'Accept-Language: fr-FR,fr;q=0.8,en;q=0.5,en-US;q=0.3';
	$headers[] = 'Connection: keep-alive';
	$headers[] = 'Origin": https://foeen.innogamescdn.com';
	$headers[] = 'Content-Type: application/json';
	$headers[] = 'Content-length: '.strlen($post);
	$headers[] = 'X-Requested-With: ShockwaveFlash/25.0.0.148';
	$headers[] = 'Referer: https://foeen.innogamescdn.com/swf/Preloader.swf?'.$time.'/[[DYNAMIC]]/1';
	$headers[] = 'Signature: '.$signature;
	$headers[] = 'Client-Identification: version=1.99; requiredVersion=1.99; platform=bro; platformVersion=web';
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_URL,$url);
	curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0");
	curl_setopt($ch, CURLOPT_COOKIEFILE, $cookie);
	curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie);
	curl_setopt($ch, CURLOPT_VERBOSE, 1);
	curl_setopt($ch, CURLOPT_NOBODY, 0);
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
  	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST"); 
  	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
	curl_setopt($ch,CURLOPT_HEADER,0);
	$linkhtml=curl_exec($ch);
	curl_close($ch);
	return $linkhtml;
}

?>

**Comment by cfHxqA** [comment]
The problem will be your signature in header. The signature changes with each request. You must find the function that generates the signature. ;)

**Comment by kimil14** [comment]
thanks my function generates the signature:

$payload = [
	"__class__" => "ServerRequest",
	"requestClass" => "StartupService",
	"requestData" => [],
	"requestId" => 0,
	"requestMethod" => "getData"
];
//$code[1] = get.h
$signature = md5($code[1]."UqO1UDI2SsDYiL/l1sANc/xCeiOXtMw5TQvcgAJgEBmcbNFbG+zS0HvqoQSOBFfRENW+JmfutSmK/8J/UsnZgw==".json_encode($payload));

This is not correct as a function? thank you in advance

**Comment by kimil14** [comment]
new error: [{"title":"Exception","message":"D\u00e9sol\u00e9, une erreur interne est survenue. Veuillez r\u00e9essayer plus tard.","__class__":"Error"}]

**Comment by cfHxqA** [comment]
Np. 

Your signature function is still wrong - and requests return then invalid request. The "signature function" generates an hash, you must reserve the apk / ios file for more infomration. ;)

**Comment by kimil14** [comment]
I changed my function like this:

$signature = md5($code[1]."forgeofempires"."[".json_encode($payload)."]");

OK for the generation an hash but why does it give me the result anyway?

**Comment by cfHxqA** [comment]
Looks better. ;)
