### ISSUE TITLE
Virus surprise in last version ...

### ISSUE THREAD

**Issue by BGTecu** [cfHxqA/InnoGames.FoE.Bot#23]
**The latest version comes with a little surprise...**

First of all it doesn't work, because of the version. And secondly it is infected with a virus...

I think the only thing the creator cares about is making money on this free platform. Not even the source code is shared... 

[**Bot.exe**](https://www.virustotal.com/gui/file/bc7f64c42d1a0da0dae93c297d0f9de6d5a3c9b4ec7b3d0882f1625d649dd706/detection)

**Comment by cfHxqA** [comment]
Dude, it based on obfuscation. The project exists still a few years. You can could try it with vm to test it. ;)
