### ISSUE TITLE
Does not login

### ISSUE THREAD

**Issue by piyushpaliwal** [cfHxqA/InnoGames.FoE.Bot#24]
I am trying this for the first time and upon updating data to the configuration files, it just won't log me in. Am I doing something wrong?

How is the server name defined? Are they like "en1", "en2", etc.?

**Comment by cfHxqA** [comment]
Already fixed with uploaded patch. 👍

**Comment by viperdriver2000** [comment]
can you update the linux zip?
FoE-Bot-linux.zip	InnoGames.FoE.Bot - Updated (v1.142.0.0)	8 months ago

**Comment by cfHxqA** [comment]
Thanks for the information! I'll try to update the linux-version today!
