### ISSUE TITLE
New polish option is not working for Guild and Friends

### ISSUE THREAD

**Issue by rcmpayne** [cfHxqA/InnoGames.FoE.Bot#5]
Run the script and wait until all the polish items are done. I gave it another 30 mins after. Login to the game and see that it polished all the neighbors but none in guild tab or friends tab

**Comment by cfHxqA** [comment]
Did you send someone an invitation or a friend request? Because that is ignored.

**Comment by rcmpayne** [comment]
no, i am in a guild and those users are not working

**Comment by cfHxqA** [comment]
Thank you! I will look for the problem.

**Comment by cfHxqA** [comment]
Fixed. New options are added. See in configuration the attribute '**game_socialbar_type_polish**'. 

**Legend:**

- 0 = All
- 1 = Friends
- 2 = Guild members
- 3 = Neighbours
