### ISSUE TITLE
my bot doesnt do anything

### ISSUE THREAD

**Issue by robinhugy** [cfHxqA/InnoGames.FoE.Bot#7]
please help, my bot doesnt do anything, i configured redownloaded 5 hours ago and started but is doesnt do his job
rarely do a job but if i join to the game from browser, i have uncollected money and some producted material
i hope you can understand my shitty english :|

**Comment by cfHxqA** [comment]
Regards, please use the latest version (1.9.7.7). 

This free version does only do collect 3x residential, 1x production. ;-) The full version contains all features, which are listen - without any limitions.

**Comment by robinhugy** [comment]
then is useless, thanks for your answer

**Comment by robinhugy** [comment]
deleting true messages?
sad :(

**Comment by cfHxqA** [comment]
Why? :octocat:
